In [1]:
import numpy as np

In [ ]:
b= np.zeros(3)
b

array([0., 0., 0.])

In [ ]:
c= np.ones(2)
c

array([1., 1.])

In [ ]:
d= np.empty(3)
d

array([0., 0., 0.])

In [4]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

1

In [5]:
## type of array
a.ndim

1

In [7]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
## type of array
b.ndim

2

In [ ]:
len(b)

3

In [ ]:
b[0]

array([1, 2, 3])

In [10]:
d  = np.array([[1,2,3,]])
d


array([[1, 2, 3]])

In [ ]:
b[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

# 3-D array
## Tensor Flow