# NUMPY PRACTICE SESSION

In [1]:
import numpy as np

In [4]:
food = np.array(['samosa' , 'pakora'])
food

array(['samosa', 'pakora'], dtype='<U6')

In [8]:
price=np.array([10, 5])
price

array([10,  5])

In [10]:
# type of array
price.ndim

1

In [11]:
len(food)

2

In [13]:
price[1]

5

In [15]:
price.mean()

7.5

In [17]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.empty(5)

array([2.12199579e-314, 4.67296746e-307, 5.57306049e-321, 3.79442416e-321,
       1.03341195e-311])

In [21]:
np.arange(10, 15)

array([10, 11, 12, 13, 14])

In [23]:
np.arange(10,40,5)

array([10, 15, 20, 25, 30, 35])

In [25]:
np.arange(1,5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [28]:
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
np.ones(10, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [33]:
np.ones(10,dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# ARRAY FUNCTIONS

In [35]:
a = np.array([1, 2.4 ,5.9])
a

array([1. , 2.4, 5.9])

In [41]:
a.sort
a

array([1. , 2.4, 5.9])

In [38]:
b= np.array([4, 9, 3.7])
b

array([4. , 9. , 3.7])

In [43]:
# CANCATENATE
c=np.concatenate((a,b))
c

array([1. , 2.4, 5.9, 4. , 9. , 3.7])

In [45]:
c.sort()
c

array([1. , 2.4, 3.7, 4. , 5.9, 9. ])

# 2-D ARRAYS

In [54]:
a = np.array([[1, 2.4 ,5.9],[4, 9, 3.7]])
a


array([[1. , 2.4, 5.9],
       [4. , 9. , 3.7]])

In [55]:
b= np.array([[4, 5, 6],[7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [50]:
d=np.concatenate((a,b),axis=0 )
d

array([1. , 2.4, 5.9, 4. , 9. , 3.7])

In [56]:
e=np.concatenate((a,b),axis=1 )
e

array([[1. , 2.4, 5.9, 4. , 5. , 6. ],
       [4. , 9. , 3.7, 7. , 8. , 9. ]])

In [60]:
f=np.array([[[1,2,3],[2,4,5],[7,8,9]]])
f

array([[[1, 2, 3],
        [2, 4, 5],
        [7, 8, 9]]])

In [61]:
f.ndim

3

In [63]:
f.size

9

In [64]:
a.shape

(2, 3)

In [66]:
f=np.array([[[1,2,3],[1,2,3]],
            [[2,4,5],[7,8,9]],
            [[2,4,5],[7,8,9]]])
f

array([[[1, 2, 3],
        [1, 2, 3]],

       [[2, 4, 5],
        [7, 8, 9]],

       [[2, 4, 5],
        [7, 8, 9]]])

In [72]:
a= np.arange(4)
a

array([0, 1, 2, 3])

In [74]:
b=a.reshape(2,2)
b

array([[0, 1],
       [2, 3]])

## convert 1-D array to 2-D array   

In [85]:
a = np.array([1, 2 ,3,4])
a

array([1, 2, 3, 4])

In [78]:
a.shape

(4,)

In [80]:
b=a[np.newaxis, :]
b

array([[1, 2, 3, 4]])

In [82]:
b=a[: ,np.newaxis]  # column wise conversion
b

array([[1],
       [2],
       [3],
       [4]])

In [86]:
a.sum()
a

array([1, 2, 3, 4])